local targetedAbilityProfileRows = {
    {"Bow", "Firework Bow", "Charged Shot", 0, 1350, 1, 0.12, false, "Bow.Firework Bow.ChargedShot", 0},
    {"Bow", "Firework Bow", "Finale", 2, 1350, 12.5, 0.12, false, "Bow.Firework Bow.Finale", 0},
    {"Bow", "Normal Wooden Bow", "Charged Shot", 0, 1350, 0.8, 0.12, false, "Bow.Normal Wooden Bow.ChargedShot", 0},
    {"Bow", "Watergun", "Water Blast", 0, 260, 0.75, 5.85, true, "Bow.Watergun.ChargedShot", 0},
    {"Bow", "Watergun LE", "Charged Shot", 0, 260, 2.6, 20.35, true, "Bow.Watergun LE.ChargedShot", 0},
    {"Bow", "Watergun LE", "Hydro Beam", 4, 60, 20, 0.12, false, "Bow.Watergun LE.Hypershot", 0},
    {"Bow", "Wooden Bow", "Charged Shot", 0, 1350, 0.8, 0.12, false, "Bow.Wooden Bow.ChargedShot", 0},
    {"Bow", "Wooden Bow", "Arrow Rain", 2, 1350, 10, 0.12, false, "Bow.Wooden Bow.ArrowRain", 0},
    {"Elements", "Air", "Air Punch", 1, 350, 4, 0.12, false, "Elements.Air.AirPalm", 0},
    {"Elements", "Air", "Shurikens", 2, 350, 10, 0.12, false, "Elements.Air.Shurikens", 3.9},
    {"Elements", "Angel", "Barrage of Light", 3, 500, 8, 8.35, true, "Elements.Angel.AwakenedMoves.BarrageOfLight", 0},
    {"Elements", "Angel", "Angelic Plunge", 4, 100, 4, 0.12, false, "Elements.Angel.AwakenedMoves.AngelicPlunge", 0},
    {"Elements", "Angel", "Lux", 4, 350, 12, 5.35, true, "Elements.Angel.Lux", 0},
    {"Elements", "Astra", "Aether Wand", 0, 250, 0.25, 0.12, false, "Elements.Astra.AetherWand", 0},
    {"Elements", "Astra", "Asterism", 1, 400, 3, 0.12, false, "Elements.Astra.Asterism", 0},
    {"Elements", "Astra", "Shooting Star", 2, 600, 6, 12.35, true, "Elements.Astra.ShootingStar", 0},
    {"Elements", "Astra", "Guiding Light", 3, 450, 8, 0.12, false, "Elements.Astra.GuidingLight", 0},
    {"Elements", "Astra", "Deliverance", 5, 500, 12, 0.12, false, "Elements.Astra.Deliverance", 0},
    {"Elements", "BootlegPhantom", "Paper Punch", 1, 350, 1.5, 0.12, false, "Elements.BootlegPhantom.AirPalm", 0},
    {"Elements", "BootlegPhantom", "Paper Shurikens", 2, 350, 1, 0.12, false, "Elements.BootlegPhantom.Shurikens", 3.9},
    {"Elements", "BootlegSolar", "Blazing Sunlar", 1, 350, 5, 0.12, false, "Elements.BootlegSolar.BlazingSunlar", 0},
    {"Elements", "BootlegSolar", "Sunlar Drive", 2, 600, 10, 12.35, true, "Elements.BootlegSolar.SunlarDrive", 0},
    {"Elements", "BootlegSolar", "Orbital Sunlar", 3, 350, 5, 0.12, false, "Elements.BootlegSolar.OrbitingSunlar", 2.85},
    {"Elements", "BootlegSolar", "Sunlar Nova", 5, 300, 15, 0.12, false, "Elements.BootlegSolar.SunlarNova", 0},
    {"Elements", "Bunny", "Divekick", 0, 300, 0.6, 0.12, false, "Elements.Bunny.Eggkick", 0},
    {"Elements", "Bunny", "Egg-Fist Blast", 2, 350, 7, 0.12, false, "Elements.Bunny.EggFistBlast", 0},
    {"Elements", "Bunny", "Eggsplosive Missles", 4, 600, 8, 8.35, true, "Elements.Bunny.EggsplosiveMissles", 0},
    {"Elements", "Bunny", "Eggsplosion Enigma", 5, 50, 4, 0.12, false, "Elements.Bunny.EggsplosionEnigma", 0},
    {"Elements", "Darkness", "Void Crush", 1, 500, 5, 0.12, false, "Elements.Darkness.VoidCrush", 0},
    {"Elements", "Darkness", "Nova", 2, 500, 8, 0.12, false, "Elements.Darkness.Nova", 0},
    {"Elements", "Darkness", "Nightfall Rupture", 4, 500, 4, 0.12, false, "Elements.Darkness.NightFallRupture", 0},
    {"Elements", "Darkness", "GhoulStorm Mines", 5, 500, 11, 8.35, true, "Elements.Darkness.GhoulStormMines", 0},
    {"Elements", "Dragon", "Draconic Fury [M1]", 0, 600, 9, 0.12, false, "Elements.Dragon.AwakenedMoves.DraconicFury", 0},
    {"Elements", "Dragon", "Flamethrower", 1, 500, 2, 2.35, false, "Elements.Dragon.AwakenedMoves.Flamethrower", 0},
    {"Elements", "Dragon", "Dragon's Horns", 2, 350, 7, 0.12, false, "Elements.Dragon.DragonsHorn", 0},
    {"Elements", "Dragon", "Roar", 2, 600, 5, 5.35, false, "Elements.Dragon.AwakenedMoves.Roar", 0},
    {"Elements", "Dragon", "Acidic Spit", 3, 350, 12, 0.12, false, "Elements.Dragon.AcidicSpit", 0},
    {"Elements", "Dragon", "Fire Blast", 3, 600, 5, 0.12, false, "Elements.Dragon.AwakenedMoves.Fire Blast", 0},
    {"Elements", "Dragon", "Dragon's Eye", 4, 500, 12, 0.12, false, "Elements.Dragon.DragonsEye", 0},
    {"Elements", "Dragon", "Fireball Shower", 4, 1000, 8, 8.35, true, "Elements.Dragon.AwakenedMoves.Fireball Shower", 0},
    {"Elements", "Dragon", "Draconic Eruption", 5, 500, 18, 8.35, true, "Elements.Dragon.DraconicEruption", 0},
    {"Elements", "Earth", "Ground Stomp", 1, 350, 9, 0.12, false, "Elements.Earth.GroundStomp", 0},
    {"Elements", "Earth", "Earth Attack", 2, 500, 8, 0.12, false, "Elements.Earth.EarthAttack", 2.9},
    {"Elements", "Earth", "Earth Dragon", 3, 500, 6, 0.12, false, "Elements.Earth.EarthDragon", 0},
    {"Elements", "Fire", "Fireball", 1, 350, 4, 0.12, false, "Elements.Fire.Fireball", 0},
    {"Elements", "Fire", "Inferno Rounds", 3, 350, 10, 8.35, true, "Elements.Fire.InfernoRounds", 0},
    {"Elements", "Galaxy", "Galactic Blast", 1, 350, 5, 0.12, false, "Elements.Galaxy.GalacticBlast", 0},
    {"Elements", "Galaxy", "Neutron Star", 1, 500, 8, 0.12, false, "Elements.Galaxy.AwakenedMoves.NeutronStar", 0},
    {"Elements", "Galaxy", "Dimensional Phase", 2, 600, 8, 12.35, true, "Elements.Galaxy.DimensionalPhase", 0},
    {"Elements", "Galaxy", "Galactic Destruction", 3, 500, 8, 10.35, true, "Elements.Galaxy.GalacticDestruction", 0},
    {"Elements", "Galaxy", "Gamma Burst", 3, 265, 10, 0.12, false, "Elements.Galaxy.AwakenedMoves.GammaBurst", 0},
    {"Elements", "Galaxy", "Quasar", 4, 220, 10, 0.12, false, "Elements.Galaxy.AwakenedMoves.Quasar", 0},
    {"Elements", "Galaxy", "Starfall", 5, 280, 15, 0.12, false, "Elements.Galaxy.AwakenedMoves.Starfall", 0},
    {"Elements", "Gravity", "Gravity Push", 1, 50, 5, 0.12, false, "Elements.Gravity.Push", 0},
    {"Elements", "Gravity", "Singularity", 1, 500, 5, 0.12, false, "Elements.Gravity.AwakenedMoves.Singularity", 0},
    {"Elements", "Gravity", "Meteor", 2, 350, 4, 0.12, false, "Elements.Gravity.Meteor", 0},
    {"Elements", "Gravity", "Gravity Pull", 3, 50, 5, 0.12, false, "Elements.Gravity.Pull", 0},
    {"Elements", "Gravity", "Gravity Well", 3, 300, 12, 8.35, true, "Elements.Gravity.AwakenedMoves.GravityWell", 0},
    {"Elements", "Gravity", "10x Domain", 4, 300, 14, 8.35, false, "Elements.Gravity.AwakenedMoves.TenXDomain", 0},
    {"Elements", "Gravity", "Planet Destroyer", 5, 450, 18, 0.12, false, "Elements.Gravity.AwakenedMoves.PlanetDestroyer", 0},
    {"Elements", "Gravity", "Planetary Barrage", 5, 400, 10, 8.35, true, "Elements.Gravity.MeteorBarrage", 0},
    {"Elements", "Ice", "Ice Barrage", 1, 350, 8, 0.12, false, "Elements.Ice.IceBarrage", 2.9},
    {"Elements", "Ice", "Ice Shurikens", 2, 350, 10, 8.35, true, "Elements.Ice.IceShurikens", 0},
    {"Elements", "Ice", "Frozen Domain", 4, 350, 13, 0.12, false, "Elements.Ice.FrozenDomain", 0},
    {"Elements", "Ice", "Absolute Zero", 5, 500, 16, 0.12, false, "Elements.Ice.AbsoluteZero", 0},
    {"Elements", "Infinity", "Collapsing Blue", 2, 350, 5, 0.12, false, "Elements.Infinity.CollapsingBlue", 0},
    {"Elements", "Infinity", "Maximum Red Output", 3, 500, 7, 0.12, false, "Elements.Infinity.MaximumRedOutput", 0},
    {"Elements", "Infinity", "Hollow Purple", 5, 250, 10, 0.12, false, "Elements.Infinity.HollowPurple", 0},
    {"Elements", "Kitsune", "Claw Slash [M1]", 0, 500, 1, 0.12, false, "Elements.Kitsune.ClawSlash", 0},
    {"Elements", "Kitsune", "Fox Bomb", 1, 2000, 6, 0.12, false, "Elements.Kitsune.FoxBomb", 0},
    {"Elements", "Kitsune", "Claw Spin", 2, 500, 5, 10.35, true, "Elements.Kitsune.ClawSpin", 0},
    {"Elements", "Kitsune", "Fox Shock", 4, 5000, 8, 0.12, false, "Elements.Kitsune.FoxShock", 0},
    {"Elements", "Krampus", "Candy Cane Slash [M1]", 0, 250, 0.15, 0.12, false, "Elements.Krampus.CandyCaneSlash", 0},
    {"Elements", "Krampus", "Peppermint Revenge", 1, 450, 5, 0.12, false, "Elements.Krampus.PeppermintRevenge", 0},
    {"Elements", "Krampus", "Glacial Shuriken Storm", 2, 450, 9, 0.12, false, "Elements.Krampus.GlacialShurikenStorm", 2.85},
    {"Elements", "Lava", "Lava Strike", 1, 600, 5, 0.12, false, "Elements.Lava.LavaStrike", 0},
    {"Elements", "Lava", "Magma Phase", 3, 100, 5, 0.12, false, "Elements.Lava.MagmaPhase", 0},
    {"Elements", "Lava", "Lava Rain", 4, 350, 8, 3.35, true, "Elements.Lava.LavaRain", 0},
    {"Elements", "Light", "Light Shot", 1, 150, 4, 0.12, false, "Elements.Light.LightShot", 0},
    {"Elements", "Light", "Light Kick", 2, 100, 6, 0.12, false, "Elements.Light.LightKick", 0},
    {"Elements", "Light", "Light Ray", 3, 300, 10, 6.35, true, "Elements.Light.LightRay", 0},
    {"Elements", "Light", "Light Barrage", 5, 300, 12, 8.35, true, "Elements.Light.LightBarrage", 0},
    {"Elements", "Lightning", "Raging Thunderstorm", 1, 500, 4, 0.12, false, "Elements.Lightning.AwakenedMoves.RagingThunderstorm", 0},
    {"Elements", "Lightning", "Thunderstrike", 1, 150, 6, 0.12, false, "Elements.Lightning.Thunderstrike", 0},
    {"Elements", "Lightning", "Lightning Dash", 2, 120, 7, 0.12, false, "Elements.Lightning.LightningDash", 0},
    {"Elements", "Lightning", "Piercing Lightning", 2, 400, 5, 1.85, true, "Elements.Lightning.AwakenedMoves.PiercingLightning", 0},
    {"Elements", "Lightning", "Lightning Chain", 3, 125, 10, 0.12, false, "Elements.Lightning.LightningChain", 0},
    {"Elements", "Lightning", "Thunderclap Drive", 3, 200, 6, 0.12, false, "Elements.Lightning.AwakenedMoves.ThunderclapDrive", 0},
    {"Elements", "Lightning", "Lightning Fury", 4, 350, 12, 8.35, true, "Elements.Lightning.LightningFury", 0},
    {"Elements", "Lightning", "Smite", 4, 500, 8, 8.35, true, "Elements.Lightning.AwakenedMoves.Smite", 0},
    {"Elements", "Lightning", "Thunderous Nova", 5, 350, 12, 0.12, false, "Elements.Lightning.ThunderousNova", 0},
    {"Elements", "Lunar", "Crescent Slash", 0, 500, 0.1, 0.12, false, "Elements.Lunar.CrescentSlash", 0},
    {"Elements", "Lunar", "Yue", 2, 300, 8, 0.12, false, "Elements.Lunar.Yue", 0},
    {"Elements", "Mech", "Laser Beam [M1]", 0, 500, 0.6, 0.12, false, "Elements.Mech.M1", 0},
    {"Elements", "Mech", "Afterburner Blast", 4, 500, 6, 17.85, true, "Elements.Mech.AfterburnerBlast", 0},
    {"Elements", "Moonlar", "Crescent Slash", 0, 375, 0.6, 0.12, false, "Elements.Moonlar.CrescentSlash", 0},
    {"Elements", "Moonlar", "Yue", 2, 300, 8, 0.12, false, "Elements.Moonlar.Yue", 0},
    {"Elements", "Nature", "Nature Beam [M1]", 0, 150, 2, 0.12, false, "Elements.Nature.M1", 0},
    {"Elements", "Nature", "Tornado", 1, 350, 8, 0.12, false, "Elements.Nature.Tornado", 0},
    {"Elements", "Nature", "Nature Arrow", 2, 200, 6, 0.12, false, "Elements.Nature.NatureArrow", 0},
    {"Elements", "Nature", "Nature Missle", 3, 600, 12, 8.35, true, "Elements.Nature.NatureMissle", 0},
    {"Elements", "Nature", "Nature's Fury", 4, 600, 14, 0.12, false, "Elements.Nature.NatureFury", 0},
    {"Elements", "Nightmare", "Shadow Grip", 1, 450, 4, 0.12, false, "Elements.Nightmare.ShadowGrip", 0},
    {"Elements", "Nightmare", "Terror Pulse", 3, 350, 8, 0.12, false, "Elements.Nightmare.TerrorPulse", 0},
    {"Elements", "Phantom", "Hand Slap [M1]", 0, 600, 1, 0.12, false, "Elements.Phantom.M1", 0},
    {"Elements", "Phantom", "Flick", 1, 350, 3, 0.12, false, "Elements.Phantom.Flick", 0},
    {"Elements", "Phantom", "Smash", 2, 150, 6, 0.12, false, "Elements.Phantom.Smash", 0},
    {"Elements", "Phantom", "Barrage", 3, 350, 12, 0.12, false, "Elements.Phantom.Barrage", 6.35},
    {"Elements", "Psychic", "Psychic Blast", 1, 350, 0.1, 0.12, false, "Elements.Psychic.PsychicBlast", 0},
    {"Elements", "Psychic", "Psychic Projectile", 2, 450, 0.1, 0.12, false, "Elements.Psychic.PsychicProjectile", 0},
    {"Elements", "Psychic", "Psychic Crush", 3, 350, 0.1, 0.12, false, "Elements.Psychic.PsychicCrush", 0},
    {"Elements", "Psychic", "Telekinesis", 5, 400, 0.1, 0.12, false, "Elements.Psychic.Telekinesis", 2.85},
    {"Elements", "Reaper", "Soul Steal", 1, 500, 5, 0.12, false, "Elements.Reaper.AwakenedMoves.Soul Steal", 0},
    {"Elements", "Reaper", "Spirit Burst", 3, 200, 8, 0.12, false, "Elements.Reaper.AwakenedMoves.Spirit Burst", 0},
    {"Elements", "Sand", "Sand Blast", 1, 350, 5, 0.12, false, "Elements.Sand.SandBlast", 0},
    {"Elements", "Sand", "Sand Tornado", 2, 350, 9, 0.12, false, "Elements.Sand.SandTornado", 0},
    {"Elements", "Smoke", "Smoke Projectile", 1, 350, 4, 0.12, false, "Elements.Smoke.SmokeProjectile", 0},
    {"Elements", "Smoke", "Smoke Rain", 3, 500, 12, 8.35, true, "Elements.Smoke.SmokeRain", 0},
    {"Elements", "Smoke", "Smoke Bomb", 4, 400, 13, 0.12, false, "Elements.Smoke.SmokeBomb", 0},
    {"Elements", "Smoke", "Smoke Missile", 5, 600, 18, 8.35, true, "Elements.Smoke.SmokeMissile", 0},
    {"Elements", "Solar", "Blazing Blast", 1, 350, 5, 0.12, false, "Elements.Solar.BlazingBlast", 0},
    {"Elements", "Solar", "Orbital Burst", 3, 350, 5, 0.12, false, "Elements.Solar.OrbitingFlames", 2.85},
    {"Elements", "Solar", "Solar Nova", 5, 300, 15, 0.12, false, "Elements.Solar.SunNova", 0},
    {"Elements", "Time", "Temporal Seam", 0, 500, 1.75, 0.12, false, "Elements.Time.TemporalSeam", 0},
    {"Elements", "Time", "Temporal Tear", 0, 500, 2, 0.12, false, "Elements.Time.TemporalTear", 0},
    {"Elements", "Time", "Flash Forward", 3, 600, 6, 0.12, false, "Elements.Time.FlashForward", 0},
    {"Elements", "Time", "Timeline Destruction", 3, 500, 6, 0.12, false, "Elements.Time.TimelineDestruction", 0},
    {"Elements", "Time", "Collapsing Rift", 4, 500, 15, 0.12, false, "Elements.Time.CollapsingRift", 0},
    {"Elements", "Water", "Roaring Wave", 1, 600, 6, 0.12, false, "Elements.Water.RoaringWave", 0},
    {"Elements", "Water", "Water Barrage", 3, 500, 16, 8.35, true, "Elements.Water.WaterBarrage", 0},
    {"Sword", "Abyssal Trident", "Abyssal Grapple", 2, 100, 2, 0.12, false, "Sword.Abyssal Trident.Throw", 0},
    {"Sword", "Ascended Lightning Katana", "Plasma Slash", 2, 350, 2, 0.12, false, "Sword.Ascended Lightning Katana.PlasmaRay", 0},
    {"Sword", "Conqueror's Blade", "Wind Dragon Force", 2, 600, 10, 8.35, true, "Sword.Conqueror's Blade.WindDragonForce", 0},
    {"Sword", "Conqueror's BladeTL", "Wind Dragon Force", 2, 600, 8, 8.35, true, "Sword.Conqueror's BladeTL.WindDragonForce", 0},
    {"Sword", "Conqueror's BladeTL", "Wind Slash", 3, 300, 6, 0.12, false, "Sword.Conqueror's BladeTL.WindSlash", 2.85},
    {"Sword", "Conqueror's BladeTL LE", "Wind Dragon Force", 2, 600, 6, 6.35, true, "Sword.Conqueror's BladeTL LE.WindDragonForce", 0},
    {"Sword", "Conqueror's BladeTL LE", "Wind Slash", 3, 300, 1.7, 0.12, false, "Sword.Conqueror's BladeTL LE.WindSlash", 2.85},
    {"Sword", "DevElemental", "Elemental Shurikens", 4, 350, 14, 0.12, false, "Sword.DevElemental", 2.85},
    {"Sword", "Elemental", "Elemental Shurikens", 4, 350, 14, 0.12, false, "Sword.Elemental", 2.85},
    {"Sword", "Fusion", "Elemental Shurikens", 4, 350, 14, 0.12, false, "Sword.Fusion", 2.85},
    {"Sword", "GlitchedStaff", "Homing Bolt", 0, 350, 1, 0.12, false, "Sword.GlitchedStaff", 0},
    {"Sword", "Lightning Katana", "Plasma Slash", 2, 350, 2, 0.12, false, "Sword.Lightning Katana.PlasmaRay", 0},
    {"Sword", "Poseidon's Trident", "Trident Grapple", 2, 100, 8, 0.12, false, "Sword.Poseidon's Trident.Throw", 0},
    {"Sword", "Rhitta", "Blazing Rain", 3, 300, 22, 0.12, false, "Sword.Rhitta.BlazingRain", 0},
    {"Sword", "Rhitta", "Maximum Nova", 4, 300, 30, 4.05, false, "Sword.Rhitta.MaximumNova", 0},
    {"Sword", "SeriousStaff", "Sunlar Bolt", 0, 375, 1, 0.12, false, "Sword.SeriousStaff.SeriousSwing", 0},
    {"Sword", "SeriousStaff", "WE are Wumpus", 3, 600, 10, 12.35, true, "Sword.SeriousStaff.SeriousDrive", 0},
    {"Sword", "ViltronStaff", "Homing Bolt", 0, 300, 1, 0.12, false, "Sword.ViltronStaff", 0},
    {"Sword", "Voidblade", "Ember Fireball", 4, 350, 14, 0.12, false, "Sword.Voidblade", 2.85},
    {"Sword", "WilbertStaff", "Sunlar Bolt", 0, 900, 1, 0.12, false, "Sword.WilbertStaff.SeriousSwing", 0},
    {"Sword", "WilbertStaff", "Lar", 5, 1500, 10, 0.12, false, "Sword.WilbertStaff.AngryDms", 0},
}
